# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='boday',
            new_name='body',
        ),
    ]
